
services:
  frontend-service:
    build: ./frontend
    ports:
      - 3001:3000
    container_name: frontend_compose
    #network_mode: "host"
    #network_mode: host

  backend-service:
    build: ./backend
    ports:
      - 8001:8000
    container_name: backend_compose
    #network_mode: host
    
  database:
    image: postgres:16.6
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    container_name: pg_db
    #network_mode: host

volumes:
  pgdata:

# networks:
#   internal:
#     driver: bridge

#   host:
#     driver: host

  # external:
  #   driver: host


    